package io.hamlook.aetheria.features.events;

import com.google.gson.Gson;
import io.hamlook.aetheria.Aetheria;
import io.hamlook.aetheria.DebugLogger;
import io.hamlook.aetheria.core.ATHRConfig;
import io.hamlook.aetheria.core.StorageManager;
import io.hamlook.aetheria.network.NetworkGuard;
import io.hamlook.aetheria.repo.CapeAPI;
import io.hamlook.aetheria.utils.ThreadUtils;
import io.hamlook.aetheria.utils.data.SkyblockData;

import java.io.BufferedReader;
import java.io.File;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Fetch/cache utility for the Fakepixel SkyBlock event schedule (Traveling Zoo, Dark Auction,
 * Farming Contest, etc.).
 * <p>
 * Source priority, cheapest/most-trusted first:
 * <ol>
 *     <li>Whatever's already cached, as long as it still has future entries — never refetches
 *     while this holds, regardless of where the data came from.</li>
 *     <li>capeapi, retried about once a minute once the cache runs dry — its Farming Contest crop
 *     data is confirmed wrong at the source, so those crops are stripped on the way in; everything
 *     else (event type + timing) is trusted.</li>
 *     <li>The yearly template bundled with the mod (a fixed JSON asset, {@link TemplateEntry}
 *     entries), if the API is unreachable/disabled and nothing is cached — the same ~372 SkyBlock
 *     days repeat every year, so this never needs to change once captured. Read-only at runtime —
 *     shipped once as a classpath resource, never written or regenerated by the mod itself.
 *     Doesn't include crops, since those aren't fixed by the yearly structure. Current (month,
 *     day, time-of-day) is read once off the live scoreboard to know where in the template "now"
 *     falls.</li>
 *     <li>Nothing — if the bundled template is somehow missing, this shows an empty list rather
 *     than a guessed one.</li>
 * </ol>
 * Reactive only — {@link #maybeRefetch()} is meant to be called from a periodic tick (see
 * {@code EventNotifierTracker}), not from a dedicated background scheduler.
 */
public class EventUtils {

    private static final long EMPTY_RETRY_INTERVAL_MS = 60_000L;
    private static final long SKYBLOCK_DAY_MS = 20 * 60_000L;
    private static final int DAYS_PER_MONTH = 31;
    private static final int DAYS_PER_YEAR = 12 * DAYS_PER_MONTH;

    private static final File CACHE_FILE = new File(ATHRConfig.configDirectory, "events_cache.json");
    private static final Gson gson = new Gson();

    public static volatile List<SkyblockEvent> cachedEvents = Collections.emptyList();

    private static volatile long lastFetchMs = 0L;
    private static volatile boolean fetchInFlight = false;

    static {
        String cached = StorageManager.loadSafeRaw(CACHE_FILE);
        List<SkyblockEvent> parsed = cached != null ? parseEvents(cached) : null;
        if (parsed != null && !parsed.isEmpty()) {
            cachedEvents = parsed;
        }
    }

    private EventUtils() {}

    /**
     * Adopts a fresh event list from a real {@link CalendarParser} walk — accurate crops included,
     * trusted for the rest of the SkyBlock year (see {@link #hasFutureEvents()}), so no more API
     * calls happen until this genuinely runs dry.
     */
    public static void adoptParsedEvents(List<SkyblockEvent> events) {
        cachedEvents = events;
        StorageManager.saveAtomicRaw(CACHE_FILE, gson.toJson(events));
    }

    public static boolean hasFutureEvents() {
        long now = System.currentTimeMillis();
        for (SkyblockEvent e : cachedEvents) {
            if (e == null || e.start == null) continue;
            try {
                if (Instant.parse(e.start).toEpochMilli() > now) return true;
            } catch (Exception ignored) {}
        }
        return false;
    }

    public static void maybeRefetch() {
        if (hasFutureEvents()) return;

        if (!NetworkGuard.apiAllowed()) {
            maybeGenerateFromTemplate();
            return;
        }
        if (fetchInFlight) return;
        long now = System.currentTimeMillis();
        if (now - lastFetchMs < EMPTY_RETRY_INTERVAL_MS) return;
        fetchAsync();
    }

    private static void fetchAsync() {
        fetchInFlight = true;
        lastFetchMs = System.currentTimeMillis();
        ThreadUtils.run("ATHR-EventUtils-Fetch", () -> {
            try {
                URL url = new URL(CapeAPI.getAPIUrl("events?type=all"));
                HttpURLConnection conn = (HttpURLConnection) url.openConnection();
                conn.setRequestMethod("GET");
                conn.setRequestProperty("User-Agent", "Aetheria/" + Aetheria.VERSION);
                conn.setRequestProperty("x-mod-secret", CapeAPI.getModSecret());
                conn.setRequestProperty("Accept", "application/json");
                conn.setConnectTimeout(5000);
                conn.setReadTimeout(5000);

                if (conn.getResponseCode() == 200) {
                    String json = readResponse(conn);
                    List<SkyblockEvent> parsed = parseEvents(json);
                    if (parsed != null) {
                        stripFarmingContestCrops(parsed);
                        cachedEvents = parsed;
                        StorageManager.saveAtomicRaw(CACHE_FILE, gson.toJson(parsed));
                        DebugLogger.log("[Events] Fetched " + parsed.size() + " events from capeapi (Farming Contest crops stripped — not trusted)");
                    } else {
                        onFetchFailed();
                    }
                } else {
                    DebugLogger.log("[Events] Fetch returned HTTP " + conn.getResponseCode());
                    onFetchFailed();
                }
            } catch (Exception e) {
                DebugLogger.log("[Events] Fetch failed: " + e.getMessage());
                onFetchFailed();
            } finally {
                fetchInFlight = false;
            }
        });
    }

    private static void onFetchFailed() {
        if (!hasFutureEvents()) maybeGenerateFromTemplate();
    }

    private static void stripFarmingContestCrops(List<SkyblockEvent> events) {
        for (SkyblockEvent e : events) {
            if (e != null && e.event != null && "Farming Contest".equals(e.event.event)) {
                e.event.crops = null;
            }
        }
    }

    private static List<SkyblockEvent> parseEvents(String json) {
        try {
            SkyblockEvent[] events = gson.fromJson(json, SkyblockEvent[].class);
            return events != null ? Arrays.asList(events) : null;
        } catch (Exception e) {
            Aetheria.logger.warning("[ATHR] Failed to parse events JSON: " + e.getMessage());
            return null;
        }
    }

    private static String readResponse(HttpURLConnection conn) throws Exception {
        try (BufferedReader reader = new BufferedReader(new InputStreamReader(conn.getInputStream(), StandardCharsets.UTF_8))) {
            StringBuilder sb = new StringBuilder();
            String line;
            while ((line = reader.readLine()) != null) sb.append(line);
            return sb.toString().trim();
        }
    }

    // ---- Yearly template: read-only at runtime, sourced from a file bundled with the mod ----

    /** {@code month} 1-12, {@code day} 1-31 — same numbering {@link CalendarParser} already uses
     *  (month = calendar page, day = day-in-page). No crops here on purpose: those are rolled per
     *  real occurrence, not fixed by the yearly template, so a template-generated event's crops
     *  stay unknown until an actual parse or (crop-stripped) API fetch covers it. */
    public static class TemplateEntry {
        public int month;
        public int day;
        public String event;
    }

    private static final String BUNDLED_TEMPLATE_PATH = "/assets/aetheria/data/events_template.json";

    private static List<TemplateEntry> loadTemplate() {
        String raw = readBundledTemplate();
        if (raw == null) return Collections.emptyList();
        try {
            TemplateEntry[] arr = gson.fromJson(raw, TemplateEntry[].class);
            return arr != null ? Arrays.asList(arr) : Collections.emptyList();
        } catch (Exception e) {
            return Collections.emptyList();
        }
    }

    private static String readBundledTemplate() {
        try (InputStream in = EventUtils.class.getResourceAsStream(BUNDLED_TEMPLATE_PATH)) {
            if (in == null) return null;
            try (BufferedReader reader = new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8))) {
                StringBuilder sb = new StringBuilder();
                String line;
                while ((line = reader.readLine()) != null) sb.append(line);
                return sb.toString();
            }
        } catch (Exception e) {
            return null;
        }
    }

    private static final Pattern SEASON_DATE = Pattern.compile(
            "(?:(Early|Late) )?(Spring|Summer|Fall|Winter) (\\d{1,2})(?:st|nd|rd|th)");
    private static final Pattern TIME_OF_DAY = Pattern.compile("(\\d{1,2}):(\\d{2})\\s*(am|pm)", Pattern.CASE_INSENSITIVE);

    /** API unreachable/disabled and nothing cached — regenerate from the saved yearly template,
     *  anchored to the current (month, day, time-of-day) read once off the live scoreboard.
     *  Deliberately does nothing if no template exists yet: an incorrect countdown is worse than
     *  none, and a real parse is what teaches this the year's structure in the first place. */
    private static void maybeGenerateFromTemplate() {
        List<TemplateEntry> template = loadTemplate();
        if (template.isEmpty()) return;

        int[] monthDay = readCurrentMonthDay();
        if (monthDay == null) return;

        long now = System.currentTimeMillis();
        long dayStartMs = now - readElapsedInSkyblockDay();
        long curAbsoluteDay = (long) (monthDay[0] - 1) * DAYS_PER_MONTH + monthDay[1];

        List<SkyblockEvent> generated = new ArrayList<>();
        for (TemplateEntry t : template) {
            long day = (long) (t.month - 1) * DAYS_PER_MONTH + t.day;
            long offsetDays = day - curAbsoluteDay;
            if (offsetDays < 0) offsetDays += DAYS_PER_YEAR;
            long startMs = dayStartMs + offsetDays * SKYBLOCK_DAY_MS;
            if (startMs <= now) continue;

            SkyblockEvent event = new SkyblockEvent();
            event.start = Instant.ofEpochMilli(startMs).toString();
            event.end = Instant.ofEpochMilli(startMs + 60_000L).toString();
            event.event = new EventInfo();
            event.event.event = t.event;
            generated.add(event);
        }

        if (!generated.isEmpty()) {
            cachedEvents = generated;
            StorageManager.saveAtomicRaw(CACHE_FILE, gson.toJson(generated));
            DebugLogger.log("[Events] Generated " + generated.size() + " event(s) from the saved yearly template (capeapi unavailable)");
        }
    }

    /** Scoreboard shows e.g. "Early Spring 1st", "Summer 15th", "Late Fall 9th" — there's no "Mid"
     *  prefix at all, the middle third of a season just has no prefix word. Early/(none)/Late give
     *  +0/+1/+2 months within Spring/Summer/Fall/Winter (season base month 0/3/6/9), giving month
     *  1-12 directly. */
    private static int[] readCurrentMonthDay() {
        for (String line : SkyblockData.getCleanScoreboardLines()) {
            Matcher m = SEASON_DATE.matcher(line);
            if (!m.find()) continue;

            int seasonBase;
            switch (m.group(2)) {
                case "Spring": seasonBase = 0; break;
                case "Summer": seasonBase = 3; break;
                case "Fall": seasonBase = 6; break;
                default: seasonBase = 9; break;
            }
            int partOffset;
            String prefix = m.group(1);
            if ("Early".equals(prefix)) partOffset = 0;
            else if ("Late".equals(prefix)) partOffset = 2;
            else partOffset = 1; // no prefix at all => middle third of the season

            return new int[]{seasonBase + partOffset + 1, Integer.parseInt(m.group(3))};
        }
        return null;
    }

    /** If the scoreboard also shows a clock (not guaranteed), this refines which fraction of the
     *  current 20-real-minute SkyBlock day has already elapsed. Falls back to "start of day" —
     *  the accepted imprecision for this fallback path only. */
    private static long readElapsedInSkyblockDay() {
        for (String line : SkyblockData.getCleanScoreboardLines()) {
            Matcher m = TIME_OF_DAY.matcher(line);
            if (!m.find()) continue;

            int hour = Integer.parseInt(m.group(1)) % 12;
            if ("pm".equalsIgnoreCase(m.group(3))) hour += 12;
            int minute = Integer.parseInt(m.group(2));
            double fractionOfDay = (hour * 60 + minute) / 1440.0;
            return (long) (fractionOfDay * SKYBLOCK_DAY_MS);
        }
        return 0L;
    }
}
